language: node_js
node_js:
  - '8'
env:
  - CODE_TESTS_WORKSPACE="$TRAVIS_BUILD_DIR/test/data"
before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export CXX="g++-4.9" CC="gcc-4.9" DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sleep 3;
    fi
branches:
  only:
    - master
cache:
  directories:
    - node_modules
    - .vscode-test
install:
 - npm install
script:
  - tslint -p .
  - npm run compile
  - npm run test --silent