language: node_js
node_js:
  - '8'
  - '10'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
    - .vscode-test
install:
 - npm install
script:
  - tslint -p .
  - npm run compile
  - npm run test --silent